[custom]

sniffer:
    enable: true
    sniffing: [tls, http]
    skip-domain: ['Mijia Cloud', dlg.io.mi.com, +.apple.com, '*.baidu.com','mtalk.google.com','*-mtalk.google.com','dl.l.google.com','dl.google.com']   #'mtalk.google.com'为fcm
    force-domain: [google.com]   #这里的+为全局嗅探
    port-whitelist: [80, 443]
hosts:
    dns.google: 8.8.8.8
    dns.alidns.com: 223.5.5.5
    doh.pub: 1.12.12.12
    doh.opendns.com: 208.67.222.222
    mtalk.google.com 142.250.157.188
    alt1-mtalk.google.com 142.250.141.188
    alt2-mtalk.google.com 142.250.115.188
    alt3-mtalk.google.com 64.233.171.188
    alt4-mtalk.google.com 173.194.202.188
    alt5-mtalk.google.com 142.250.141.188 
    alt6-mtalk.google.com 142.250.115.188 
    alt7-mtalk.google.com 142.250.141.188
    alt8-mtalk.google.com 142.250.152.188  
    dl.google.com 180.163.151.161
    dl.l.google.com 180.163.150.33
dns:
    enable: true
    prefer-h3: true
    use-hosts: true
    use-system-hosts: true
    ipv6: false
    listen: 1053
    enhanced-mode: fake-ip
    fake-ip-range: 28.0.0.1/8
    fake-ip-filter: ['*', +.lan, +.local, mtalk.google.com, mtalk4.google.com, mtalk-staging.google.com, mtalk-dev.google.com, alt1-mtalk.google.com, alt2-mtalk.google.com, alt3-mtalk.google.com, alt4-mtalk.google.com, alt5-mtalk.google.com, alt6-mtalk.google.com, alt7-mtalk.google.com, alt8-mtalk.google.com]
    nameserver: ['https://8.8.4.4/dns-query', 'https://8.8.8.8/dns-query', 'https://1.1.1.1/dns-query', 'https://208.67.222.222/dns-query']
    default-nameserver: [223.5.5.5, 119.29.29.29]
    nameserver-policy: { 'geosite:cn,private,apple': ['https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'https://1.12.12.12/dns-query'] }
    proxy-server-nameserver: ['https://8.8.4.4/dns-query', 'https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'https://1.12.12.12/dns-query']

      

ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaDNS/ChinaDNS.list

;谷歌FCM使用host加速
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list

;steam-cn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

;google-cn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
;谷歌
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list




;YouTube
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KKTV/KKTV.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LiTV/LiTV.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOHK/HBOHK.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.list
;TikTok
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
;Line
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
;📲 电报消息
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
;微软
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list



ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPsBGP/ChinaIPsBGP.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN


ruleset=🚀 节点选择,[]FINAL



custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`.*
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🎥 流媒体解锁`select`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT


enable_rule_generator=true
overwrite_original_rules=true
