[custom]

dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://dns.pub/dns-query
    
  ;代理节点域名解析服务器，仅用于解析代理节点的域名
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    
    
  fallback:
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.gvt1.com



;Notion
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Notion/Notion.list
;Ⓜ️ 必应
ruleset=🧠 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list



;仅广告联盟 无副作用
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;知乎
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.list

;隐私保护 2W+
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.list
;广告精简版 3W+
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list


ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/accelerated-domains.china.list

;中国dns
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaDNS/ChinaDNS.list



ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XianYu/XianYu.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MeiTuan/MeiTuan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Eleme/Eleme.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SMZDM/SMZDM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AliPay/AliPay.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Zhihu/Zhihu.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LanZouYun/LanZouYun.list



;游戏下载
ruleset=🎯 全球直连,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list

;steam
;steam代理，可能会影响到后面的下载cdn
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
;EA
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list

;R星
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Rockstar/Rockstar.list
;蒸汽平台
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list

;使steam确认ip归属为cn
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/cn-steam.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/cn-steam2.list




;游戏下载、
;steam国内cdn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/gamedownload.list
;各种游戏下载
ruleset=🎯 全球直连,https://raw.githubusercontent.com/LoveMyself666/ACL4SSR/master/Clash/GameDownload.list

;steam海外cdn游戏下载，;如果游戏平台是使用国外的cdn 游戏下载
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/oversea-gamedownload.list

;epic直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list

;各种游戏平台加速
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/LoveMyself666/ACL4SSR/master/Clash/GamePlatform.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list




;国内cdn下载，里面包含了各种平台包括steam，阿里，华为
ruleset=🎯 全球直连,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/direct-cdn-download.list



;OpenAI
ruleset=🧠 OpenAI,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/openai.list





ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list


;github,谷歌服务默认自动选择
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
;github默认自动选择
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list



;📢 谷歌FCM默认♻️ 自动选择
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list



ruleset=🚀 手动切换,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list


;Line
ruleset=🚀 手动切换,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.list
;微软
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
;苹果全部域名
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list

;github
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list

;📲 电报消息
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list

;TikTok
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list


ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list

;台湾流媒体
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KKTV/KKTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LiTV/LiTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list

;bilibili
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ZJU-Rule/ZJU-Rule/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list

;国外媒体
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list

;亚马逊
ruleset=♻️ 自动选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.list

;下载
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
;PT种子
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list

;ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMaxNoIP/ChinaMaxNoIP.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPsBGP/ChinaIPsBGP.list
ruleset=🎯 全球直连,[]GEOIP,CN

ruleset=🐟 漏网之鱼,[]FINAL


;设置规则标志位





;设置分组标志位



custom_proxy_group=🚀 手动切换`select`.*


custom_proxy_group=🎥 流媒体解锁`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|netflix|nf|nfo|allmedia|媒体)
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🚀 手动切换
custom_proxy_group=📹 油管视频`select`[]♻️ 自动选择`[]🇨🇳 送中节点(无广告)`[]🚀 手动切换
custom_proxy_group=🧠 OpenAI`select`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]♻️ 自动选择`[]🚀 手动切换`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT


;低倍率节点
custom_proxy_group=🎮 游戏平台`url-test`(?=.*)^((?!(x4|x5|x6|x7|x8|x9|x10|x15|x20|送中|NAT|nat|Nat)).)*$`http://www.gstatic.com/generate_204`300,,200

;改手动选择
;custom_proxy_group=🧠 OpenAI`url-test`(?=.*)^((?!(x10|x20|x15|港|HK|Hong Kong|🇭🇰|HongKong|澳门|MO|mo|Mo|Macao|🇲🇴|新加坡|坡|狮城|SG|Singapore|送中|NAT|nat|Nat)).)*$`http://cp.cloudflare.com/generate_204`30,,150


;不选高倍率,台湾流媒体解锁
custom_proxy_group=📺 台湾流媒体`url-test`^(?=.*(?:台|新北|彰化|TW|Taiwan|tw))(?=.*(?:NF|奈飞|解锁|Netflix|NETFLIX|Media|netflix|nf|nfo|allmedia|媒体|送中|NAT|nat|Nat))(?!.*(?:x10|x20|x15)).*$`http://cp.cloudflare.com/generate_204`30,,150

;不选高倍率
custom_proxy_group=♻️ 自动选择`url-test`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🔯 故障转移`fallback`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🔮 负载均衡`load-balance`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=✈️ 自动选择`url-test`.*`http://cp.cloudflare.com/generate_204`30,,100   #300为interv时间间隔，150为torlerance




;不选高倍率
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(港|HK|Hong Kong|🇭🇰|HongKong))^((?!(x10|x20|x15|莞港)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(?=.*(台|新北|彰化|TW|Taiwan|tw))^((?!(x10|x20|x15|莞港)).)*$`http://cp.cloudflare.com/generate_204`30,,150


custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|MO|mo|Mo|Macao|🇲🇴)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇨🇳 送中节点(无广告)`url-test`(?=.*(中|油管无广告))^((?!(x10|x20|x15)).)*$`http://cp.cloudflare.com/generate_204`30,,150



;

;custom_proxy_group=🌍 国外媒体`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎥 Disney+`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎥 PrimeVideo`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换

;custom_proxy_group=♻️ 自动选择`url-test`(?=.*(港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|KR|Korea|KOR|首尔|韩|韓|澳门|MO|mo|Mo|Macao|🇲|德|英|法兰克福|伦敦|uk))^((?!(x10|x20|x15|莞港)).)*$`http://www.gstatic.com/generate_204`30,,150
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://captive.apple.com/generate_204`30,,150   #300为interv时间间隔，150为torlerance
;custom_proxy_group=🔯 故障转移`fallback`.*`http://captive.apple.com/generate_204`30,,150
;custom_proxy_group=🔮 负载均衡`load-balance`.*`http://captive.apple.com/generate_204`30,,150
;默认自动选择custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
;默认自动选择custom_proxy_group=🟡 谷歌服务`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
;custom_proxy_group=📺 台湾媒体`select`[]🇨🇳 台湾节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://captive.apple.com/generate_204`30,,150
;custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan|tw)`http://captive.apple.com/generate_204`30,,50
;custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
;并入国外媒体custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
;custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
;custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
;custom_proxy_group=⏱ Speedtest`select`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎵 TikTok`select`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇲🇴 澳门节点`[]🇰🇷 韩国节点`[]DIRECT`




;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ZJU-Rule/ZJU-Rule/master/Clash/GeneralClashConfig.yml

;luck
