[custom]
# port: 7890
# socks-port: 7891
# redir-port: 7892
# tproxy-port: 7893
mixed-port: 7899
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9091




;国内ip已在ros上分流完成，所以这里全部代理就行，不用再考虑要不要分流


ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list




ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
;亚马逊
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.list
;onedrive可能对网速有要求
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
;icloud/appstore
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppStore/AppStore.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloud/iCloud.list


;newbing
ruleset=🧠 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
;OPENAI
ruleset=🧠 OpenAI,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/openai.list


;流媒体解锁-网飞/迪士尼
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🎥 流媒体解锁,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hulu/Hulu.list


;bilibili应该不生效
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ZJU-Rule/ZJU-Rule/master/Clash/Ruleset/BilibiliHMT.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list

;香港流媒体
ruleset=📺 香港流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVB/TVB.list
ruleset=📺 香港流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/myTVSUPER/myTVSUPER.list


;台湾流媒体
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KKTV/KKTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LiTV/LiTV.list
ruleset=📺 台湾流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list

;日本流媒体
ruleset=🗻 日本流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
ruleset=🗻 日本流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.list
ruleset=🗻 日本流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Peacock/Peacock.list
;不确定是不是日本
ruleset=🗻 日本流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PandoraTV/PandoraTV.list
;日本游戏
ruleset=🗻 日本流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.list







;消耗大流量
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/LoveMyself666/ACL4SSR/master/Clash/GamePlatform.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/HAOLANYANG/clash_rule/main/rules/oversea-gamedownload.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Ubisoft/Ubisoft.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NGA/NGA.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Battle/Battle.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Rockstar/Rockstar.list

;能上就行
;微软
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
;Notion
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Notion/Notion.list
;苹果
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
;谷歌
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
;github
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
;谷歌FCM
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
;TG
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
;推特
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list


;国外媒体大杂锦
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list

ruleset=🐟 漏网之鱼,[]FINAL

;设置规则标志位






;设置分组标志位
custom_proxy_group=🚀 节点选择`select`♻️ 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`(?=.*)^((?!(不合适线路|剩余|天|重置|流量)).)*$
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点
custom_proxy_group=🎥 流媒体解锁`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点


custom_proxy_group=🧠 OpenAI`select`[]🚀 节点选择`(?=.*)^((?!(不合适线路|剩余|天|重置|流量)).)*$
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`(?=.*)^((?!(不合适线路|剩余|天|重置|流量|专线|IPLC|IEPL|PNAC|iplc|iepl|x4|x5|x6|x7|x8|x9|x10|x15|x20|送中|NAT|nat|Nat)).)*$
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择


;不选高倍率,地区流媒体解锁
custom_proxy_group=📺 香港流媒体`select`[]🇭🇰 香港节点
custom_proxy_group=📺 台湾流媒体`select`[]🇹🇼 台湾节点
custom_proxy_group=🗻 日本流媒体`select`[]🇯🇵 日本节点

;不选高倍率
custom_proxy_group=♻️ 自动选择`url-test`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat|不合适线路|剩余|天|重置|流量)).)*$`http://cp.cloudflare.com/generate_204`30,,150
;custom_proxy_group=🔯 故障转移`fallback`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat|不合适线路|剩余|天|重置|流量)).)*$`http://cp.cloudflare.com/generate_204`30,,150
;custom_proxy_group=🔮 负载均衡`load-balance`(?=.*)^((?!(x6|x7|x8|x9|x10|x20|x15|送中|NAT|nat|Nat|不合适线路|剩余|天|重置|流量)).)*$`http://cp.cloudflare.com/generate_204`30,,150



;地区选择-不选高倍率
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(港|HK|Hong Kong|🇭🇰|HongKong))^((?!(x10|x20|x15|莞港|不合适线路)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇹🇼 台湾节点`url-test`(?=.*(台|新北|彰化|TW|Taiwan|tw))^((?!(x10|x20|x15|莞港|不合适线路)).)*$`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore|sg)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|jp)`http://cp.cloudflare.com/generate_204`30,,150
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`300,,150


;custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|MO|mo|Mo|Macao|🇲🇴)`http://cp.cloudflare.com/generate_204`30,,150
;custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓|kr)`http://cp.cloudflare.com/generate_204`30,,150
;custom_proxy_group=🇨🇳 送中节点(无广告)`url-test`(?=.*(中|油管无广告))^((?!(x10|x20|x15)).)*$`http://cp.cloudflare.com/generate_204`30,,150

;custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🚀 节点选择
;custom_proxy_group=🎯 全球直连`select`[]DIRECT




